version: '2.4'

services:

    netscanner:
        image: registry.messner.click/gunny26/docker-netscanner:latest
        container_name: netscanner
        restart: no
        mem_limit: 128m
        cpu_count: 2
        privileged: true
        network_mode: host
        environment:
            TZ: Europe/Vienna
            APP_LOG_LEVEL: INFO
